name: motodealz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.10+1

# Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  connectivity_plus: ^6.0.1
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  dots_indicator: ^2.1.1
  image_picker: ^0.8.4+2

  
  #Firebase
  firebase_core: ^2.25.5
  otp_text_field: ^1.1.3
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  lottie: ^3.1.0
  firebase_storage: ^11.7.0


  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
   


  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Sample car/Audi A4/
    - assets/images/Sample car/Audi A5/
    - assets/images/Sample car/BMW X5/
    - assets/images/Sample car/Chevrolet camaro/
    - assets/images/Sample car/Chevrolet Malibu/
    - assets/images/Sample car/Ford f-150/
    - assets/images/Sample car/Ford fiesta/
    - assets/images/Sample car/Ford mustang/
    - assets/images/Sample car/Honda civic/
    - assets/images/Sample car/Mercedes-Benz/
    - assets/images/Sample car/Toyota corolla/
    - assets/images/Sample car/Toyota tacoma/
    - assets/images/Sample car/Volkswagen golf/
    - assets/logos/
    - assets/logos/popular_brand/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-SemiBold.ttf
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

