// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbGj7mxujW-hHjRJgVGExfSGdK9wMtjJc',
    appId: '1:946874732653:web:fd09b4ba08376925576f64',
    messagingSenderId: '946874732653',
    projectId: 'motodealz-7badd',
    authDomain: 'motodealz-7badd.firebaseapp.com',
    storageBucket: 'motodealz-7badd.appspot.com',
    measurementId: 'G-TTVXVBSC3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6pNH1C3ouOq1K88R64_xY_dt-qT2_j9c',
    appId: '1:946874732653:android:3ef33dedc562e75e576f64',
    messagingSenderId: '946874732653',
    projectId: 'motodealz-7badd',
    storageBucket: 'motodealz-7badd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7V4YzYpmAOKBlpX6chvD--EF1C0AkxI',
    appId: '1:946874732653:ios:d8f2b071a5471cc2576f64',
    messagingSenderId: '946874732653',
    projectId: 'motodealz-7badd',
    storageBucket: 'motodealz-7badd.appspot.com',
    androidClientId: '946874732653-datlad88no4nkttro8c6offd94r9p4uq.apps.googleusercontent.com',
    iosClientId: '946874732653-o1jahlb3ejkdfjnjtc9ft1qb6s82s05r.apps.googleusercontent.com',
    iosBundleId: 'com.example.motodealz',
  );
}
